# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YApQ-dBtKUe9IY9qr6fOxBstPq3IMG3h
"""

!pip install -U langchain langchain-google-genai langchain-community langsmith langchain-chroma

"""**API Key from Google Colab Secrets**"""

from google.colab import userdata
key = userdata.get('GeminiLangChain')

print(key)

"""**Web Scraping**"""

# Web Page Loader
from langchain_community.document_loaders import WebBaseLoader
loader = WebBaseLoader("https://docs.langchain.com/oss/python/langchain/rag")
docs = loader.load()

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=100,
    chunk_overlap=10
    )

splits = text_splitter.split_documents(docs)

print(len(splits))

"""**Add Docs to VectorDB**"""

from langchain_community.embeddings import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_chroma import Chroma

vectorstore = Chroma(
    collection_name="my_collection",
    embedding_function=embeddings,
    persist_directory="./chroma_langchain_db"
)

print(vectorstore._collection.get(ids="ce1c328e-bfc5-49b2-90c5-6ff9c1cffd87"))

vectorstore.add_documents(splits)

print(vectorstore._collection.count())

"""**RAG - Retriever**"""

retriever = vectorstore.as_retriever()

import os
os.environ['LANGSMITH_API_KEY'] = userdata.get('LangSmith')
LangSmith_Key = os.environ['LANGSMITH_API_KEY']

from langsmith import Client
client = Client(api_key=LangSmith_Key)
prompt = client.pull_prompt("rlm/rag-prompt", include_model=True)

"""**RAG - LLM**"""

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=key
)

"""**RAG - Chain**"""

from langchain_core.prompts import ChatPromptTemplate

from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

def format_docs(docs):
  return "\n".join(doc.page_content for doc in docs)

rag_chain = ({
    "context": retriever | format_docs,
    "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser())

rag_chain.invoke("What is RAG?")